### ISSUE TITLE
Create JupyterHub unity-marketplace metadata.json

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads#1]

**Comment by GodwinShen** [comment]
@mcduffie ping for status.

**Comment by galenatjpl** [comment]
@mcduffie Hi! @pymonger will be working on creating this manifest.json

**Comment by galenatjpl** [comment]
I'm going to close this ticket, since it's a duplicate of https://github.com/unity-sds/unity-cs/issues/491
