### ISSUE TITLE
Deploy app build pipeline to test and prod shared environments

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads#7]

**Comment by mcduffie** [comment]
Getting MCP permissions for connection to Gitlab put in place.

**Comment by GodwinShen** [comment]
@mcduffie did MCP grant the right permissions to allow this work to proceed?  Here's the MCP JIRA ticket that @edwinsarkissian submitted last Monday to request the appropriate permissions: https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-3342

**Comment by GodwinShen** [comment]
Latest comment on MCP JIRA ticket GSD-3342 shows that the MCP permissions were updated as requested, please confirm.

**Comment by mcduffie** [comment]
Believe access is in place. But running into https://github.com/psf/requests/issues/6707 issue causing inability to test. Able to deploy into test, but not prod because of missing SSM params.

**Comment by mike-gangl** [comment]
[This](https://github.com/psf/requests/issues/6707) should be resolved now. This ticket is still "blocked" based on 153

**Comment by mcduffie** [comment]
Fixing connection issue to MCP

**Comment by mcduffie** [comment]
Deployment to dev and test, but not to prod because missing api-gateway setup

**Comment by mcduffie** [comment]
Final updates will be pushed into repos
