### ISSUE TITLE
[Bug]: Upgrade EKS 1.27 AMIs

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads#8]
MCP ticket was sent to me- cc'ed on them. A few ec2 instances in various venues are using an AMI that will be deprecated soon (aml2-eks-1-27) . We must upgrade to a new blessed EKS AMI (aml2-eks-1-[28-30]).

| venue | ec2 ID | 
| ---- | ---- | 
| Unity-SIPS-test   | i-018a5add1cecc7ad3|
| Unity-SIPS-test   |  i-056ce42ad3f1e1c81	  |
| Unity-SIPS-test   | i-0f88f5f3d289dc4a7	|
| Unity-SIPS-test   | i-0fb1b7e224bd240c7	|
| Unity-Venue-Dev	| i-05e472ad97c33dea9|
| Unity-Venue-Dev | 	i-04a3da8237b7d76ac	| 	
| Unity-Venue-Dev|	i-06383b7f7c6e6e216	|
| Unity-Venue-Dev|	i-065ec0b364e65f731	|
| Unity-Venue-Test|	i-02f5805ba656be245	|
| Unity-Venue-Test	| i-01d05cf95b94dc163 |
| Unity-Venue-Test|	i-02fe69385f4719393	|
|  Unity-Venue-Test|	i-0386b5e1f2afce5d3	|

**Comment by mcduffie** [comment]
Unity-Venue-Dev and Unity-Venue-Test brought up to EKS 1.30.

Unity-SIPS-test resources destroyed.
